# docker-compose.yml
version: '3.8'
services:
  database:
    image: "postgres" # use latest official postgres version
    restart: always
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5435:5432"
    expose:
      - "5435"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
